var game = new Game();
var myGrid = new Grid(8, 16, 50, game.sprites); 
game.addSprite(myGrid);
var myScore = new Score(20, 30, 'green', 'Score:');
game.addSprite(myScore);
var myPelletGenerator = new PelletGenerator();
game.addSprite(myPelletGenerator);
var myPacman = new Pacman(50, 50, 40, 40, 'yellow', 2);
game.addSprite(myPacman);
var ghostOne = new Ghost(650, 50, 40, 40, 'red', 2);
var ghostTwo = new Ghost(700, 250, 40, 40, 'pink', 2);
game.addSprite(ghostOne);
game.addSprite(ghostTwo);
game.animate();
